apiVersion: apps/v1
kind: Deployment
metadata:
  name: adkwebui
  labels:
    app: adkwebui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adkwebui
  template:
    metadata:
      labels:
        app: adkwebui
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: gcr.io/gke-hack-471804/adkwebui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: AGENT_SERVICE_URL
          value: "http://agentservice:8080"
        - name: ADK_WEBUI_PORT
          value: "8000"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: adkwebui
  labels:
    app: adkwebui
spec:
  type: ClusterIP
  selector:
    app: adkwebui
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP 