# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import imageassistant_pb2 as imageassistant__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in imageassistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageAssistantServiceStub(object):
    """Image assistant service for gRPC communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeImage = channel.unary_unary(
                '/imageassistant.ImageAssistantService/AnalyzeImage',
                request_serializer=imageassistant__pb2.AnalyzeImageRequest.SerializeToString,
                response_deserializer=imageassistant__pb2.AnalyzeImageResponse.FromString,
                _registered_method=True)
        self.VisualizeProduct = channel.unary_unary(
                '/imageassistant.ImageAssistantService/VisualizeProduct',
                request_serializer=imageassistant__pb2.VisualizeProductRequest.SerializeToString,
                response_deserializer=imageassistant__pb2.VisualizeProductResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/imageassistant.ImageAssistantService/Check',
                request_serializer=imageassistant__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=imageassistant__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ImageAssistantServiceServicer(object):
    """Image assistant service for gRPC communication
    """

    def AnalyzeImage(self, request, context):
        """Analyze image for objects, scene type, styles, colors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VisualizeProduct(self, request, context):
        """Visualize product in user photo using Gemini 2.5 Flash Image Preview
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageAssistantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeImage,
                    request_deserializer=imageassistant__pb2.AnalyzeImageRequest.FromString,
                    response_serializer=imageassistant__pb2.AnalyzeImageResponse.SerializeToString,
            ),
            'VisualizeProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.VisualizeProduct,
                    request_deserializer=imageassistant__pb2.VisualizeProductRequest.FromString,
                    response_serializer=imageassistant__pb2.VisualizeProductResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=imageassistant__pb2.HealthCheckRequest.FromString,
                    response_serializer=imageassistant__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageassistant.ImageAssistantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imageassistant.ImageAssistantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageAssistantService(object):
    """Image assistant service for gRPC communication
    """

    @staticmethod
    def AnalyzeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageassistant.ImageAssistantService/AnalyzeImage',
            imageassistant__pb2.AnalyzeImageRequest.SerializeToString,
            imageassistant__pb2.AnalyzeImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VisualizeProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageassistant.ImageAssistantService/VisualizeProduct',
            imageassistant__pb2.VisualizeProductRequest.SerializeToString,
            imageassistant__pb2.VisualizeProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageassistant.ImageAssistantService/Check',
            imageassistant__pb2.HealthCheckRequest.SerializeToString,
            imageassistant__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
