-- Populate products table with sample data for Cloud SQL
-- This script adds the original 9 products plus 6 additional onesthe

INSERT INTO products (id, name, description, picture, price_usd_currency_code, price_usd_units, price_usd_nanos, categories, target_tags, use_context) VALUES
-- Original 9 products
('OLJCESPC7Z', 'Sunglasses', 'Add a modern touch to your outfits with these sleek aviator sunglasses.', 'https://glassyeyewear.com/cdn/shop/files/walker-mblk-rm-polar-34.jpg?v=1705618525&width=1000', 'USD', 19, 990000000, 'accessories', '{men,women,unisex}', '{outdoor,casual,fashion}'),
('66VCHSJNUP', 'Tank Top', 'Perfectly cropped cotton tank, with a scooped neckline.', 'https://asrv.com/cdn/shop/files/SPACEGREY_TankTop1_1600x.jpg?v=1710530514', 'USD', 18, 990000000, 'clothing,tanks', '{women,unisex}', '{casual,fitness,summer}'),
('1YMWWN1N4O', 'Watch', 'This gold-tone stainless steel watch will work with most of your outfits.', '/static/img/products/watch.jpg', 'USD', 109, 990000000, 'accessories', '{men,women,unisex}', '{formal,casual,office}'),
('L9ECAV7KIM', 'Loafers', 'A neat addition to your summer wardrobe.', '/static/img/products/loafers.jpg', 'USD', 89, 990000000, 'footwear', '{men,women}', '{casual,summer,office}'),
('2ZYFJ3GM2N', 'Hairdryer', 'This lightweight hairdryer has 3 heat and speed settings. It''s perfect for drying your hair quickly.', '/static/img/products/hairdryer.jpg', 'USD', 24, 990000000, 'hair,beauty', '{women,unisex}', '{bathroom,personal_care}'),
('0PUK6V6EV0', 'Candle Holder', 'This small but stylish candle holder is an excellent addition to your home decor.', '/static/img/products/candle-holder.jpg', 'USD', 18, 990000000, 'decor,home', '{unisex}', '{living_room,bedroom,dining_room}'),
('LS4PSXUNUM', 'Salt & Pepper Shakers', 'Add some flavor to your kitchen.', '/static/img/products/salt-and-pepper-shakers.jpg', 'USD', 18, 990000000, 'kitchen', '{unisex}', '{kitchen,dining_room}'),
('9SIQT8TOJO', 'Bamboo Glass Jar', 'This bamboo glass jar can hold 57 oz (1.7l) and is perfect for any kitchen counter.', '/static/img/products/bamboo-glass-jar.jpg', 'USD', 5, 990000000, 'kitchen', '{unisex}', '{kitchen,storage}'),
('6E92ZMYYFZ', 'Mug', 'A simple mug with a mustard interior.', '/static/img/products/mug.jpg', 'USD', 8, 990000000, 'kitchen', '{unisex}', '{kitchen,office}'),
('CAMERA001', 'Vintage Camera', 'Capture life''s precious moments with this retro-style camera perfect for photography enthusiasts.', 'https://dfjx2uxqg3cgi.cloudfront.net/img/photo/35737/35737_00_2x.jpg?20150621115429', 'USD', 89, 990000000, 'electronics,photography', '{men,women,unisex}', '{outdoor,travel,hobby}'),
('BACKPACK01', 'Travel Backpack', 'Durable and spacious backpack ideal for hiking, traveling, and everyday adventures.', 'https://cdn.thewirecutter.com/wp-content/media/2024/04/carryontravelbackpacks-2048px-0187.jpg?auto=webp&quality=75&width=1024', 'USD', 67, 990000000, 'bags,travel', '{men,women,unisex}', '{outdoor,travel,hiking}'),
('NOTEBOOK1', 'Leather Notebook', 'Premium leather-bound notebook perfect for journaling, sketching, or taking notes.', 'https://m.media-amazon.com/images/I/81kr4gvE8xL.jpg', 'USD', 23, 990000000, 'stationery,office', '{men,women,unisex}', '{office,study,creative}'),
('SNEAKERS1', 'Running Sneakers', 'Comfortable and lightweight running shoes designed for performance and style.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPLnQxWxWCw0EJOW3VEwkNTLLc3x5AzfL_aw&s', 'USD', 78, 990000000, 'footwear,sports', '{men,women,unisex}', '{fitness,outdoor,casual}'),
('PLANTPOT1', 'Ceramic Plant Pot', 'Beautiful ceramic pot perfect for your favorite indoor plants and succulents.', 'https://m.media-amazon.com/images/I/713ZvA5hL9L.jpg', 'USD', 15, 990000000, 'decor,home,garden', '{unisex}', '{living_room,bedroom,office,garden}'),
('TSHIRT001', 'Cotton T-Shirt', 'Soft and comfortable 100% cotton t-shirt available in multiple colors.', 'https://joesusa.com/cdn/shop/files/athleticheather-front__83530__24374_8135__17315.1730584884.1280.1280.jpg?v=1743029922', 'USD', 24, 990000000, 'clothing,casual', '{men,women,unisex}', '{casual,everyday,comfort}'),

-- Home & Living Products (15 items)
('SOFA001', 'Modern Sectional Sofa', 'Comfortable L-shaped sectional sofa perfect for modern living rooms with premium fabric upholstery.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTAk20s0GXT5EPYRPQxW_7R2kdGUtH-TqPSg&s', 'USD', 899, 0, 'furniture,living_room', '{unisex}', '{living_room,comfort,entertaining}'),
('LAMP001', 'LED Floor Lamp', 'Adjustable LED floor lamp with warm white lighting, perfect for reading and ambient lighting.', 'https://i5.walmartimages.com/seo/SUNMORY-Soft-Light-LED-Floor-Lamp-RGB-Color-Changing-61-Modern-Tall-Lamp-Smart-Standing-Lamp-Remote-Control-APP-Control-Living-Room-Bedroom-Game-Room_dfdd669a-1d58-4276-ac72-94ed7025df2b.df80836937f83a5630f470559df7b08f.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF', 'USD', 89, 990000000, 'lighting,home', '{unisex}', '{living_room,bedroom,office,reading}'),
('TABLE001', 'Dining Table', 'Solid wood dining table seats 6 people comfortably, perfect for family meals and entertaining.', 'https://cdn.dashhudson.com/media/full/1728388074.73543525980.jpeg', 'USD', 549, 0, 'furniture,dining_room', '{unisex}', '{dining_room,entertaining,family}'),
('CHAIR001', 'Office Chair', 'Ergonomic office chair with lumbar support and adjustable height for comfortable work sessions.', 'https://images.thdstatic.com/productImages/c4076ea0-b946-4112-b541-88caf9eceb69/svn/brown-allwex-task-chairs-kl600-64_600.jpg', 'USD', 199, 990000000, 'furniture,office', '{unisex}', '{office,work,comfort}'),
('BED001', 'Queen Bed Frame', 'Minimalist wooden bed frame with built-in nightstands and storage drawers underneath.', 'https://softframedesigns.com/cdn/shop/files/Ultrabedwhitefront_grande.webp?v=1737053689', 'USD', 449, 990000000, 'furniture,bedroom', '{unisex}', '{bedroom,sleep,storage}'),
('MIRROR001', 'Wall Mirror', 'Large decorative wall mirror with ornate frame, adds elegance to any room.', 'https://m.media-amazon.com/images/I/71iZ-FBr5HL._UF894,1000_QL80_.jpg', 'USD', 129, 990000000, 'decor,home', '{unisex}', '{bedroom,bathroom,living_room}'),
('CURTAINS1', 'Blackout Curtains', 'Thermal blackout curtains that block 99% of light, perfect for bedrooms and media rooms.', 'https://i5.walmartimages.com/seo/Deconovo-Thermal-Insulated-Grommet-Blackout-Curtains-for-Bedroom-Black-42-x-63-2-Panels_6d0d6760-103a-4eaf-840e-dc6030e28022.eeeeb17b2a53eaeef93f9f219247020f.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF', 'USD', 39, 990000000, 'home,decor', '{unisex}', '{bedroom,living_room,privacy}'),
('RUG001', 'Area Rug', 'Soft Persian-style area rug adds warmth and character to living spaces.', 'https://nazmiyalantiquerugs.com/wp-content/uploads/2016/06/tribal-colorful-rug-in-home-decor-nazmiyal-antique-rugs.jpg', 'USD', 159, 990000000, 'decor,home', '{unisex}', '{living_room,bedroom,comfort}'),
('SHELF001', 'Bookshelf', 'Five-tier wooden bookshelf perfect for displaying books, plants, and decorative items.', 'https://assets.weimgs.com/weimgs/ab/images/wcm/products/202512/0003/otto-bookshelf-33-53-o.jpg', 'USD', 89, 990000000, 'furniture,storage', '{unisex}', '{office,living_room,bedroom,storage}'),
('VASE001', 'Ceramic Vase', 'Handcrafted ceramic vase with modern geometric design, perfect for fresh or dried flowers.', 'https://fleurings.com/cdn/shop/products/41Z0qsgOWzL.jpg?v=1692228965', 'USD', 34, 990000000, 'decor,home', '{unisex}', '{living_room,bedroom,dining_room}'),
('PILLOW001', 'Throw Pillows', 'Set of 2 decorative throw pillows with removable covers in trendy patterns.', 'https://acamporainteriors.com/wp-content/uploads/2021/03/sofa-throw-pillows-featured-1.jpg', 'USD', 29, 990000000, 'decor,home', '{unisex}', '{living_room,bedroom,comfort}'),
('BLANKET1', 'Weighted Blanket', 'Therapeutic weighted blanket promotes better sleep and reduces anxiety.', 'https://funandfunction.com/media/catalog/product/cache/e9d548ef5405886a511cf82578fc34f7/c/f/cf6443_001.jpg', 'USD', 79, 990000000, 'bedding,wellness', '{unisex}', '{bedroom,sleep,relaxation}'),
('CLOCK001', 'Wall Clock', 'Modern minimalist wall clock with silent movement, perfect for any room.', 'https://www.ikea.com/us/en/images/products/pluttis-wall-clock-red__1013097_pe829051_s5.jpg', 'USD', 45, 990000000, 'decor,home', '{unisex}', '{living_room,office,bedroom}'),
('DIFFUSER1', 'Essential Oil Diffuser', 'Ultrasonic aromatherapy diffuser creates calming atmosphere with your favorite essential oils.', 'https://m.media-amazon.com/images/I/71fq8cLk2ZL.jpg', 'USD', 49, 990000000, 'wellness,home', '{unisex}', '{bedroom,living_room,relaxation}'),
('OTTOMAN1', 'Storage Ottoman', 'Multi-functional storage ottoman serves as seating, footrest, and storage solution.', 'https://scandinaviandesigns.com/cdn/shop/products/H12_TOBI_STORAGE_OTTOMAN_CH_01.jpg?v=1721224259', 'USD', 69, 990000000, 'furniture,storage', '{unisex}', '{living_room,bedroom,storage}'),

-- Kitchen & Dining Products (10 items)
('BLENDER1', 'High-Speed Blender', 'Professional-grade blender perfect for smoothies, soups, and food preparation.', 'https://i5.walmartimages.com/seo/Ninja-Twisti-High-Speed-Blender-Duo-3-Preset-Auto-iQ-Programs-34-oz-Pitcher-Capacity-SS150_998555c3-207a-4333-a645-04481a4fef4b.29ba39c0e3b175711caae8d69a939862.png', 'USD', 149, 990000000, 'kitchen,appliances', '{unisex}', '{kitchen,cooking,healthy}'),
('KNIFE001', 'Chef Knife Set', 'Professional 8-piece knife set with wooden block, essential for any home cook.', 'https://fusionlayers.us/wp-content/uploads/2021/10/Steel-9-Knife-Sets-all-images-1.jpg', 'USD', 89, 990000000, 'kitchen,cooking', '{unisex}', '{kitchen,cooking,professional}'),
('PAN001', 'Non-Stick Pan Set', 'Set of 3 non-stick frying pans in different sizes with ceramic coating.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpL3-NrbpJLqWhFf76l_G_Xs0OdSlHGXFrPw&s', 'USD', 79, 990000000, 'kitchen,cookware', '{unisex}', '{kitchen,cooking,healthy}'),
('PLATES01', 'Dinnerware Set', '12-piece dinnerware set includes plates, bowls, and mugs for 4 people.', 'https://m.media-amazon.com/images/I/716ncF3r9ML.jpg', 'USD', 59, 990000000, 'kitchen,dining', '{unisex}', '{kitchen,dining_room,entertaining}'),
('MIXER001', 'Stand Mixer', 'Powerful stand mixer with multiple attachments for baking and cooking.', 'https://dimg.dillards.com/is/image/DillardsZoom/main/cuisinart-5.5-quart-stand-mixer/00000000_zi_1dee9032-fe4b-4758-870f-1260543920c2.jpg', 'USD', 299, 990000000, 'kitchen,appliances', '{unisex}', '{kitchen,baking,cooking}'),
('KETTLE01', 'Electric Kettle', 'Fast-boiling electric kettle with temperature control and automatic shut-off.', 'https://m.media-amazon.com/images/I/71zJShDoPsL.jpg', 'USD', 39, 990000000, 'kitchen,appliances', '{unisex}', '{kitchen,tea,coffee}'),
('CUTTING1', 'Cutting Board Set', 'Bamboo cutting board set with juice grooves and built-in compartments.', 'https://assets.wsimgs.com/wsimgs/ab/images/dp/wcm/202520/0227/img2o.jpg', 'USD', 34, 990000000, 'kitchen,tools', '{unisex}', '{kitchen,cooking,food_prep}'),
('STORAGE1', 'Food Storage Containers', 'Set of 10 glass food storage containers with airtight lids.', 'https://cdn.thewirecutter.com/wp-content/media/2025/04/BEST-FOOD-STORAGE-CONTAINERS-2048px-0861.jpg', 'USD', 49, 990000000, 'kitchen,storage', '{unisex}', '{kitchen,storage,meal_prep}'),
('COFFEE01', 'Coffee Maker', 'Programmable drip coffee maker brews perfect coffee every morning.', 'https://m.media-amazon.com/images/I/71LB1AbsorL.jpg', 'USD', 89, 990000000, 'kitchen,appliances', '{unisex}', '{kitchen,morning,coffee}'),
('WINE001', 'Wine Glasses', 'Set of 4 elegant wine glasses perfect for entertaining and special occasions.', 'https://media.royaldesign.com/2/spiegelau-salute-red-wine-glass-set-of-4-55-cl-13?w=800&quality=80', 'USD', 29, 990000000, 'kitchen,dining', '{unisex}', '{dining_room,entertaining,celebration}'),

-- Fashion & Accessories (15 items)
('DRESS001', 'Summer Dress', 'Flowing midi dress in breathable fabric, perfect for warm weather and casual outings.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA7Tta1V52O84drr_3hWSZ9Iar4IotvHyJ3Q&s', 'USD', 59, 990000000, 'clothing,dresses', '{women}', '{casual,summer,outdoor}'),
('JACKET01', 'Leather Jacket', 'Classic black leather jacket adds edge to any outfit, suitable for all seasons.', 'hhttps://thursdayboots.com/cdn/shop/files/1024x1024-Mens-Keanu-Black-010924-1_1024x1024.jpg?v=1705095642', 'USD', 189, 990000000, 'clothing,outerwear', '{men,women,unisex}', '{casual,fashion,outdoor}'),
('JEANS001', 'Skinny Jeans', 'Comfortable stretch denim jeans with perfect fit and classic styling.', 'https://example.com/jeans.jpg', 'USD', 69, 990000000, 'clothing,pants', '{men,women,unisex}', '{casual,everyday,fashion}'),
('SCARF001', 'Silk Scarf', 'Luxurious silk scarf with artistic print, versatile accessory for any season.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6us6wFZw4aAscki_1KHOqR6X29NX9vPng-w&s', 'USD', 45, 990000000, 'accessories,fashion', '{women,unisex}', '{fashion,office,casual}'),
('HAT001', 'Baseball Cap', 'Adjustable cotton baseball cap with embroidered logo, perfect for casual wear.', 'https://store.moma.org/cdn/shop/files/3a2b0b12-bde3-4a63-bba2-b561dbd7de29_5fa67989-c4a0-4bea-a74b-fb25ed894895.jpg?v=1710971142', 'USD', 24, 990000000, 'accessories,hats', '{men,women,unisex}', '{casual,outdoor,sports}'),
('BOOTS001', 'Ankle Boots', 'Comfortable ankle boots with low heel, perfect for work and weekend wear.', 'https://www.rocketdog.com/cdn/shop/files/york_santee_pu_brown_002.jpg?v=1736858407&width=1946', 'USD', 89, 990000000, 'footwear,boots', '{women,unisex}', '{casual,office,fashion}'),
('BELT001', 'Leather Belt', 'Genuine leather belt with classic buckle, essential accessory for any wardrobe.', 'https://azbelt.com/cdn/shop/products/mochaclassicfront_938x.jpg?v=1614274667', 'USD', 39, 990000000, 'accessories,belts', '{men,women,unisex}', '{formal,casual,office}'),
('PURSE001', 'Crossbody Bag', 'Compact crossbody bag with multiple compartments, perfect for daily essentials.', 'https://www.incase.com/cdn/shop/files/INCO400721-BLK_INCASE_SOUP_08_20_202445271.png?v=1733859841&width=2048', 'USD', 79, 990000000, 'bags,accessories', '{women,unisex}', '{casual,travel,everyday}'),
('SWEATER1', 'Wool Sweater', 'Cozy wool sweater with cable knit pattern, perfect for cooler weather.', 'https://i.ebayimg.com/images/g/6uQAAOSwnHNilBX7/s-l1200.jpg', 'USD', 89, 990000000, 'clothing,knitwear', '{women,unisex}', '{casual,winter,comfort}'),
('SHORTS01', 'Athletic Shorts', 'Moisture-wicking athletic shorts with built-in compression liner.', 'https://examphttps://i.ebayimg.com/images/g/6uQAAOSwnHNilBX7/s-l1200.jpgle.com/shorts.jpg', 'USD', 34, 990000000, 'clothing,activewear', '{men,women,unisex}', '{fitness,sports,summer}'),
('SOCKS001', 'Wool Socks', 'Merino wool socks provide warmth and moisture management for active lifestyles.', 'https://sockdreams.com/cdn/shop/products/drs-hiking-wool-socks-brown-er-ot-2.jpg?v=1682811500&width=1920', 'USD', 19, 990000000, 'clothing,socks', '{men,women,unisex}', '{outdoor,hiking,winter}'),
('GLOVES01', 'Winter Gloves', 'Insulated winter gloves with touchscreen-compatible fingertips.', 'https://m.media-amazon.com/images/I/71qT0+XcmpL._UY1000_.jpg', 'USD', 29, 990000000, 'accessories,winter', '{men,women,unisex}', '{winter,outdoor,cold}'),
('SHIRT001', 'Button-Up Shirt', 'Classic white button-up shirt suitable for business and casual occasions.', 'https://m.media-amazon.com/images/I/81sL0fqeKbL._UY1000_.jpg', 'USD', 49, 990000000, 'clothing,shirts', '{men,women,unisex}', '{office,formal,casual}'),
('PAJAMAS1', 'Silk Pajamas', 'Luxurious silk pajama set provides ultimate comfort for restful sleep.', 'https://www.notjustpajama.com/cdn/shop/products/DSC06428.jpg?v=1755902141&width=1080', 'USD', 129, 990000000, 'clothing,sleepwear', '{women,unisex}', '{bedroom,sleep,luxury}'),
('CARDIGAN1', 'Knit Cardigan', 'Open-front knit cardigan perfect for layering in transitional weather.', 'https://cozyearth.com/cdn/shop/files/1_Oxford_Oversizedcableknitcardigan.jpg?v=1754675379&width=1600', 'USD', 64, 990000000, 'clothing,knitwear', '{women,unisex}', '{casual,office,layering}'),

-- Technology & Electronics (10 items)
('PHONE001', 'Smartphone Case', 'Protective smartphone case with card holder and kickstand functionality.', 'https://cdn.thewirecutter.com/wp-content/media/2024/01/bestiphonecases-2048px-8563.jpg', 'USD', 24, 990000000, 'electronics,accessories', '{men,women,unisex}', '{everyday,protection,convenience}'),
('HEADPHONES1', 'Wireless Headphones', 'Noise-canceling wireless headphones with 30-hour battery life.', 'https://i5.walmartimages.com/seo/VILINICE-Noise-Cancelling-Headphones-Wireless-Bluetooth-Over-Ear-Headphones-with-Microphone-Black-Q8_b994b99c-835f-42fc-8094-9f6be0f9273b.be59955399cdbd1c25011d4a4251ba9b.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF', 'USD', 199, 990000000, 'electronics,audio', '{men,women,unisex}', '{music,travel,work}'),
('TABLET01', 'Tablet Stand', 'Adjustable tablet stand for comfortable viewing and video calls.', 'https://us.bouncepad.com/cdn/shop/files/Go-Blue-FrontThreeQuarterwithiPad-1x1Web.jpg?v=1687435860', 'USD', 29, 990000000, 'electronics,accessories', '{unisex}', '{office,home,entertainment}'),
('CHARGER1', 'Wireless Charger', 'Fast wireless charging pad compatible with all Qi-enabled devices.', 'https://example.com/charger.jpg', 'USD', 39, 990000000, 'electronics,charging', '{unisex}', '{office,bedroom,convenience}'),
('SPEAKER1', 'Bluetooth Speaker', 'Portable waterproof Bluetooth speaker with 360-degree sound.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBfj73H39CIgAbQHIzEvKNe5Y15Mv0MXchpw&s', 'USD', 79, 990000000, 'electronics,audio', '{unisex}', '{outdoor,travel,entertainment}'),
('KEYBOARD1', 'Mechanical Keyboard', 'RGB backlit mechanical keyboard with tactile switches for gaming and typing.', 'https://cdn.mos.cms.futurecdn.net/LAybH9XXiNwJh9VVjRax8X-1200-80.jpg', 'USD', 129, 990000000, 'electronics,computer', '{unisex}', '{office,gaming,work}'),
('MOUSE001', 'Wireless Mouse', 'Ergonomic wireless mouse with precision tracking and long battery life.', 'https://cdn.mos.cms.futurecdn.net/GttMZ84yZoqEaQcJ4vAWbd.jpg', 'USD', 49, 990000000, 'electronics,computer', '{unisex}', '{office,work,productivity}'),
('WEBCAM01', 'HD Webcam', 'Full HD webcam with auto-focus and noise-canceling microphone.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmbg6MsJYTtFYv5dGtyIo8DWfOh365npbjlg&s', 'USD', 69, 990000000, 'electronics,computer', '{unisex}', '{office,work,video_calls}'),
('POWER001', 'Power Bank', 'High-capacity portable power bank with fast charging and multiple ports.', 'https://media.wired.com/photos/6504b2a1afe02332db973557/4:3/w_960,c_limit/Ugreen_Power_Bank-SOURCE-Ugreen-Gear.jpg', 'USD', 39, 990000000, 'electronics,portable', '{unisex}', '{travel,outdoor,emergency}'),
('CABLE001', 'USB-C Cable', 'Braided USB-C cable with fast data transfer and charging capabilities.', 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/HRGS2?wid=6533&hei=5303&fmt=jpeg&qlt=90&.v=1717527834594', 'USD', 19, 990000000, 'electronics,accessories', '{unisex}', '{office,charging,connectivity}')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  picture = EXCLUDED.picture,
  price_usd_currency_code = EXCLUDED.price_usd_currency_code,
  price_usd_units = EXCLUDED.price_usd_units,
  price_usd_nanos = EXCLUDED.price_usd_nanos,
  categories = EXCLUDED.categories,
  target_tags = EXCLUDED.target_tags,
  use_context = EXCLUDED.use_context; 